services:
  # Serviço do PostgreSQL
  postgres:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
      # MANTENHA O pata APONTANDO PARA O DIRETÓRIO INTERNO DO VOLUME
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      # REFERÊNCIA AO VOLUME NOMEADO. É AQUI QUE O DOCKER GERENCIA AS PERMISSÕES.
      - postgres_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço da aplicação Go
  app:
    image: golang:1.22
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=root
      - DB_PORT=5432
    
    # Configuração para manter o contêiner rodando (bom para o exec)
    tty: true
    stdin_open: true
    command: tail -f /dev/null

    depends_on:
      # Garante que o Go espere o Postgres estar saudável antes de iniciar
      postgres:
        condition: service_healthy
volumes:
  postgres_data:

    # O Docker vai gerenciar este volume, evitando erros de permissão.
